# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Maven Package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 13.0.1
      uses: actions/setup-java@v1
      with:
        java-version: 13.0.1
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name : Maven Clean
      run : mvn -B clean --file pom.xml
      
    - name : Maven Validate
      run : mvn -B validate --file pom.xml
      
    - name : Maven Compile
      run : mvn -B compile --file pom.xml
    
    - name : Maven Test
      run : mvn -B test --file pom.xml
      
    - name: Maven - Package
      run: mvn -B package --file pom.xml
